Allow JWT 2.x (#317)
* allow jwt 2.x

* upgrade minimum ruby version, due to rubocop incompatibility:
Error: Unsupported Ruby version 2.0 found in  parameter (in .rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5